name: r8r-db

on:
  workflow_dispatch:
  push:
    paths:
      - 'db/'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: db/.
          push: true
          tags: na7r1x/r8r-db:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
